### PR TITLE
Win path support for v2

### LINKED ISSUE #52: Relative paths not recognized by remark
Hi! I've been trying to get V2 to work with Netlify CMS, but I'm stuck:
Image paths are getting transformed to relative paths, such as:

`"..\\..\\..\\static\\img\\78255412_1542951075843738_6829112130805956608_o.jpg"`

but, looking in GraphiQL, the field in frontmatter is still a string, never being transformed into an ImageSharp object.
I did put the plugin before gatsby-remark-images, so I don't know what might be happening.
I believe it might have something to do with the path module using the double slashes in windows instead of a forward slash. Gatsby/Sharp recognizes that path when using forward slashes.

Thanks for the attention.

### PR DESCRIPTION
**Pull request by Daguima-dag**
Fixes #52 
Imported and added slash function right before the outputted value in order to fix the issue of rendering double backslashes in Windows. Also changed the "rm -rf" in plugin scripts to use rimraf instead, for better windows compatibility. Also included rimraf as a dependency.

### CODE REVIEW

**Comment by gracjan-op** [comment]
@danielmahon  when it will be merged ?

**Comment by emanuele-em** [comment]
@danielmahon when it will be merged?

**Comment by elnino97** [comment]
@danielmahon when it will be merged?

**Comment by Ortimis** [comment]
@danielmahon should be merged asap, the plugin is unusable on windows currently

**Comment by elnino97** [comment]
Since this project is not maintained anymore, I would recommend to clone the plugin and branch to `daguima-dag:win-path-fix`. After that, just run `npm build` and link the plugin with the project you are using.

**Review by elnino97 — APPROVED** [review]

**Pull request merged**
