### PR TITLE
Fix overwriting other files with the same name (Fix #17)

### LINKED ISSUE #17: Subfolders in assets result in overwrite images having the same names
If there are subfolders inside `assets` which contain images have same names, like:
```
- assets
|_ sub-folder-1
|___ image1.png
|_ sub-folder-2
|___ image1.png
````
the following markdown will display `/assets/sub-folder-2/image1.png` for both of images:
````
[my-first-image](./assets/sub-folder-1/image1.png)
[my-second-image](./assets/sub-folder-2/image1.png)
````

### PR DESCRIPTION
**Pull request by hanakla**
Fix issue #17.

I checked it works in my environment, but I do not know if it works correctly in every case. Please review.

### CODE REVIEW

**Comment by sarahbethfederman** [comment]
having this issue as well. Would love to see this PR make it in!

**Comment by Zulcom** [comment]
@danielmahon please merge this request! It's a major issue fixed in your plugin!

**Comment by danielmahon** [comment]
@hanakla Thank you for this! @sarahbethfederman  @Zulcom sorry for the delay in getting this merged, haven't had a need for this recently so I keep forgetting about it 😉 ...

**Comment by danielmahon** [comment]
Shipped in 0.3.0

**Pull request merged**
